
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 12;
  public static final int MENOS = 8;
  public static final int CORIZQ = 5;
  public static final int UMENOS = 13;
  public static final int ENTERO = 11;
  public static final int POR = 9;
  public static final int CORDER = 6;
  public static final int PTCOMA = 2;
  public static final int DIVIDIDO = 10;
  public static final int EOF = 0;
  public static final int MAS = 7;
  public static final int PARIZQ = 3;
  public static final int error = 1;
  public static final int PARDER = 4;
  public static final int REVALUAR = 14;
  public static final int NOMBRE = 15;
  public static final int GBAJO = 16;
  public static final int COMA = 17;
  public static final int ASIGNACION = 18;
  public static final int AND = 19;
  public static final int FIN = 20;
  public static final int NOT = 21;
  public static final int CADENA = 22;
  public static final int NUMERO = 23;
  public static final int OR = 24;
  public static final int SI = 25;
  public static final int CARACTER = 26;
  public static final int OSI = 27;
  public static final int COMO = 28;
  public static final int FALSO = 29;
  public static final int MENOR = 30;
  public static final int MAYOR = 31;
  public static final int FINSI = 32;
  public static final int TNUMERO = 33;
  public static final int MODULO = 34;
  public static final int TCADENA = 35;
  public static final int INICIO = 36;
  public static final int TBOOLEAN = 37;
  public static final int ESIGUAL = 38;
  public static final int TCARACTER = 39;
  public static final int POTENCIA = 40;
  public static final int INGRESAR = 41;
  public static final int VERDADERO = 42;
  public static final int CONVALOR = 43;
  public static final int ESDIFERENTE = 44;
  public static final int MENOROIGUAL = 45;
  public static final int MAYOROIGUAL = 46;
  public static final int DELOCONTRARIO = 47;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "ENTERO",
  "DECIMAL",
  "UMENOS",
  "REVALUAR"
  };
 
}

